-- Migration: 028_telegram_bot
-- Description: Add tables for Telegram bot integration
-- Created: 2026-02-22

-- Temporary link codes generated by the bot (/link command)
-- User visits the web app, enters this code to link their Telegram account
CREATE TABLE IF NOT EXISTS telegram_link_tokens (
  code          TEXT PRIMARY KEY,
  telegram_id   TEXT NOT NULL,
  telegram_username TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at    TIMESTAMPTZ NOT NULL
);

-- Linked Telegram accounts
-- api_token_encrypted: raw user API token encrypted with SERVICES_SECRET_KEY
-- so the bot can make LeMedia API calls on behalf of the user
CREATE TABLE IF NOT EXISTS telegram_users (
  telegram_id         TEXT PRIMARY KEY,
  user_id             INTEGER NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  api_token_encrypted TEXT NOT NULL,
  linked_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_telegram_users_user_id ON telegram_users(user_id);
