import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requireUser } from "@/auth";
import { requireCsrf } from "@/lib/csrf";
import { logger } from "@/lib/logger";
import {
  createUserApiToken,
  getPool,
  getUserEpisodeReminderPreference,
  setUserEpisodeReminderPreference,
} from "@/db";
import { generateUserApiToken } from "@/lib/api-tokens";
import { encryptSecret } from "@/lib/encryption";
import { sendTelegramMessage } from "@/notifications/telegram";
import { isValidTimeZone } from "@/lib/app-timezone";

const LinkBody = z.object({
  code: z.string().trim().min(1).max(20)
});

const PreferenceBody = z
  .object({
    followedMediaNotifications: z.boolean().optional(),
    episodeReminderEnabled: z.boolean().optional(),
    episodeReminderPrimaryMinutes: z.number().int().min(1).max(43200).optional(),
    episodeReminderSecondEnabled: z.boolean().optional(),
    episodeReminderSecondMinutes: z.number().int().min(1).max(43200).optional(),
    episodeReminderTelegramEnabled: z.boolean().optional(),
    reminderTimezone: z.string().trim().max(100).nullable().optional(),
  })
  .refine(
    (value) =>
      value.followedMediaNotifications !== undefined ||
      value.episodeReminderEnabled !== undefined ||
      value.episodeReminderPrimaryMinutes !== undefined ||
      value.episodeReminderSecondEnabled !== undefined ||
      value.episodeReminderSecondMinutes !== undefined ||
      value.episodeReminderTelegramEnabled !== undefined ||
      value.reminderTimezone !== undefined,
    { message: "At least one preference must be provided" }
  );

// POST /api/telegram/link
// Validates a link code generated by the Telegram bot and links the
// authenticated user's LeMedia account to their Telegram account.
export async function POST(req: NextRequest) {
  const user = await requireUser();
  if (user instanceof NextResponse) return user;

  const csrf = requireCsrf(req);
  if (csrf) return csrf;

  let body: { code: string };
  try {
    body = LinkBody.parse(await req.json());
  } catch {
    return NextResponse.json({ error: "Invalid request" }, { status: 400 });
  }

  const pool = getPool();

  // Look up the link token
  const tokenRes = await pool.query(
    `SELECT telegram_id, telegram_username, expires_at
     FROM telegram_link_tokens
     WHERE code = $1`,
    [body.code.toUpperCase()]
  );

  if (tokenRes.rows.length === 0) {
    logger.warn("[TelegramLink] Code not found", { code: body.code });
    return NextResponse.json({ error: "Invalid or expired code" }, { status: 400 });
  }

  const { telegram_id, telegram_username, expires_at } = tokenRes.rows[0];

  if (new Date(expires_at) < new Date()) {
    await pool.query("DELETE FROM telegram_link_tokens WHERE code = $1", [body.code.toUpperCase()]);
    return NextResponse.json({ error: "Invalid or expired code" }, { status: 400 });
  }

  // Check if this Telegram account is already linked to a different user
  const existingRes = await pool.query(
    "SELECT user_id FROM telegram_users WHERE telegram_id = $1",
    [telegram_id]
  );
  if (existingRes.rows.length > 0 && existingRes.rows[0].user_id !== user.id) {
    return NextResponse.json(
      { error: "This Telegram account is already linked to a different user" },
      { status: 409 }
    );
  }

  // Generate an API token for the bot to use on behalf of this user
  const rawToken = generateUserApiToken();
  await createUserApiToken(user.id, "Telegram Bot", rawToken);

  // Store the encrypted raw token so the bot can retrieve it
  const encryptedToken = encryptSecret(rawToken);

  await pool.query(
    `INSERT INTO telegram_users (telegram_id, user_id, api_token_encrypted, linked_at)
     VALUES ($1, $2, $3, now())
     ON CONFLICT (telegram_id) DO UPDATE
       SET user_id = EXCLUDED.user_id,
           api_token_encrypted = EXCLUDED.api_token_encrypted,
           linked_at = now()`,
    [telegram_id, user.id, encryptedToken]
  );

  // Clean up the link token
  await pool.query("DELETE FROM telegram_link_tokens WHERE code = $1", [body.code.toUpperCase()]);

  logger.info("[TelegramLink] User linked Telegram account", {
    userId: user.id,
    username: user.username,
    telegramUsername: telegram_username
  });

  return NextResponse.json({ ok: true, telegramUsername: telegram_username });
}

// GET /api/telegram/link
// Check if the current user already has a linked Telegram account
export async function GET(_req: NextRequest) {
  const user = await requireUser();
  if (user instanceof NextResponse) return user;

  const pool = getPool();
  const res = await pool.query(
    "SELECT telegram_id, linked_at FROM telegram_users WHERE user_id = $1",
    [user.id]
  );

  if (res.rows.length === 0) {
    const prefs = await getUserEpisodeReminderPreference(user.id);
    return NextResponse.json({
      linked: false,
      followedMediaNotifications: prefs.followedMediaNotifications,
      episodeReminderEnabled: prefs.episodeReminderEnabled,
      episodeReminderPrimaryMinutes: prefs.episodeReminderPrimaryMinutes,
      episodeReminderSecondEnabled: prefs.episodeReminderSecondEnabled,
      episodeReminderSecondMinutes: prefs.episodeReminderSecondMinutes,
      episodeReminderTelegramEnabled: prefs.episodeReminderTelegramEnabled,
      reminderTimezone: prefs.reminderTimezone,
    });
  }

  const prefs = await getUserEpisodeReminderPreference(user.id);

  return NextResponse.json({
    linked: true,
    telegramId: res.rows[0].telegram_id,
    linkedAt: res.rows[0].linked_at,
    followedMediaNotifications: prefs.followedMediaNotifications,
    episodeReminderEnabled: prefs.episodeReminderEnabled,
    episodeReminderPrimaryMinutes: prefs.episodeReminderPrimaryMinutes,
    episodeReminderSecondEnabled: prefs.episodeReminderSecondEnabled,
    episodeReminderSecondMinutes: prefs.episodeReminderSecondMinutes,
    episodeReminderTelegramEnabled: prefs.episodeReminderTelegramEnabled,
    reminderTimezone: prefs.reminderTimezone,
  });
}

// PATCH /api/telegram/link
// Updates telegram-linked user preferences
export async function PATCH(req: NextRequest) {
  const user = await requireUser();
  if (user instanceof NextResponse) return user;

  const csrf = requireCsrf(req);
  if (csrf) return csrf;

  let body: {
    followedMediaNotifications?: boolean;
    episodeReminderEnabled?: boolean;
    episodeReminderPrimaryMinutes?: number;
    episodeReminderSecondEnabled?: boolean;
    episodeReminderSecondMinutes?: number;
    episodeReminderTelegramEnabled?: boolean;
    reminderTimezone?: string | null;
  };
  try {
    body = PreferenceBody.parse(await req.json());
  } catch {
    return NextResponse.json({ error: "Invalid request" }, { status: 400 });
  }

  if (body.reminderTimezone !== undefined && body.reminderTimezone !== null) {
    const trimmedTimezone = body.reminderTimezone.trim();
    if (trimmedTimezone.length > 0 && !isValidTimeZone(trimmedTimezone)) {
      return NextResponse.json({ error: "Invalid timezone" }, { status: 400 });
    }
    body.reminderTimezone = trimmedTimezone.length > 0 ? trimmedTimezone : null;
  }

  const pool = getPool();
  const linked = await pool.query(
    "SELECT telegram_id FROM telegram_users WHERE user_id = $1 LIMIT 1",
    [user.id]
  );

  const existing = await getUserEpisodeReminderPreference(user.id);
  const next = {
    followedMediaNotifications: body.followedMediaNotifications ?? existing.followedMediaNotifications,
    episodeReminderEnabled: body.episodeReminderEnabled ?? existing.episodeReminderEnabled,
    episodeReminderPrimaryMinutes: body.episodeReminderPrimaryMinutes ?? existing.episodeReminderPrimaryMinutes,
    episodeReminderSecondEnabled: body.episodeReminderSecondEnabled ?? existing.episodeReminderSecondEnabled,
    episodeReminderSecondMinutes: body.episodeReminderSecondMinutes ?? existing.episodeReminderSecondMinutes,
    episodeReminderTelegramEnabled: body.episodeReminderTelegramEnabled ?? existing.episodeReminderTelegramEnabled,
    reminderTimezone: body.reminderTimezone === undefined ? existing.reminderTimezone : body.reminderTimezone,
  };

  await setUserEpisodeReminderPreference(user.id, next);

  if (body.followedMediaNotifications && linked.rows.length > 0) {
    const botToken = String(process.env.TELEGRAM_BOT_TOKEN ?? "").trim();
    const chatId = String(linked.rows[0].telegram_id ?? "").trim();
    if (botToken && chatId) {
      try {
        await sendTelegramMessage({
          botToken,
          chatId,
          text: "You have enabled Notifications for followed media.",
        });
      } catch (err) {
        logger.warn("[TelegramLink] Failed to send followed-media preference confirmation", {
          userId: user.id,
          error: err instanceof Error ? err.message : String(err),
        });
      }
    }
  }

  return NextResponse.json({
    ok: true,
    followedMediaNotifications: next.followedMediaNotifications,
    episodeReminderEnabled: next.episodeReminderEnabled,
    episodeReminderPrimaryMinutes: next.episodeReminderPrimaryMinutes,
    episodeReminderSecondEnabled: next.episodeReminderSecondEnabled,
    episodeReminderSecondMinutes: next.episodeReminderSecondMinutes,
    episodeReminderTelegramEnabled: next.episodeReminderTelegramEnabled,
    reminderTimezone: next.reminderTimezone,
  });
}

// DELETE /api/telegram/link
// Unlinks the current user's Telegram account
export async function DELETE(req: NextRequest) {
  const user = await requireUser();
  if (user instanceof NextResponse) return user;

  const csrf = requireCsrf(req);
  if (csrf) return csrf;

  const pool = getPool();
  await pool.query("DELETE FROM telegram_users WHERE user_id = $1", [user.id]);

  logger.info("[TelegramLink] User unlinked Telegram account", { userId: user.id, username: user.username });
  return NextResponse.json({ ok: true });
}
