export const NOTIFICATION_TYPE_BIT_REQUEST_PENDING = 1;
export const NOTIFICATION_TYPE_BIT_REQUEST_SUBMITTED = 2;
export const NOTIFICATION_TYPE_BIT_REQUEST_AVAILABLE = 4;
export const NOTIFICATION_TYPE_BIT_REQUEST_DENIED = 8;
export const NOTIFICATION_TYPE_BIT_REQUEST_FAILED = 16;
export const NOTIFICATION_TYPE_BIT_MEDIA_AUTO_APPROVED = 32;
export const NOTIFICATION_TYPE_BIT_TEST_NOTIFICATION = 64;
export const NOTIFICATION_TYPE_BIT_REQUEST_PARTIALLY_AVAILABLE = 128;
export const NOTIFICATION_TYPE_BIT_REQUEST_DOWNLOADING = 256;

export const NOTIFICATION_TYPE_BIT_SYSTEM_ALERT_HIGH_LATENCY = 2048;
export const NOTIFICATION_TYPE_BIT_SYSTEM_ALERT_SERVICE_UNREACHABLE = 4096;
export const NOTIFICATION_TYPE_BIT_SYSTEM_ALERT_INDEXERS_UNAVAILABLE = 8192;

export function getNotificationTypeMaskForSystemEvent(event: string): number {
  switch (event) {
    case "system_alert_high_latency":
      return NOTIFICATION_TYPE_BIT_SYSTEM_ALERT_HIGH_LATENCY;
    case "system_alert_service_unreachable":
      return NOTIFICATION_TYPE_BIT_SYSTEM_ALERT_SERVICE_UNREACHABLE;
    case "system_alert_indexers_unavailable":
      return NOTIFICATION_TYPE_BIT_SYSTEM_ALERT_INDEXERS_UNAVAILABLE;
    default:
      return 0;
  }
}

